name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:  # Run tests on PRs
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install


  test:
    runs-on: ubuntu-20.04
    needs: build  # Ensures build completes before testing
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Run Tests
        run: yarn run coverage

  deploy:
    runs-on: ubuntu-20.04
    needs: [build, test]  # Ensures build & test complete before deploying
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploying to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app/be-test
            git fetch origin
            git pull origin main
            docker compose up --build -d
            docker system prune -f
