name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Removed 14.x (EOL)

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures build completes before deploying
    if: github.ref == 'refs/heads/main'  # Deploy only when pushing to main

    steps:
      - name: Deploying to VPS
        uses: appleboy/ssh-action@master
        with:
          host: "103.183.75.97"
          username: "dafa-workplace"
          password: "!Qazsewq123"
          port: 22
          script: |
            cd ~/apps/node1
            git pull origin main
            yarn install --production
            pm2 restart node1
